# -*- coding: utf-8 -*-
"""iris_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgcFXy2Ypk9SnsLk_76JvTRFIoz5HErj
"""

import streamlit as st
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Load the Iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Train the model
clf = RandomForestClassifier()
clf.fit(X, y)

# Streamlit app layout
st.title("🌸 Iris Flower Predictor")
st.write("Input the flower's measurements to predict its species.")

# Input sliders
sepal_length = st.slider('Sepal length (cm)', float(X.min()[0]), float(X.max()[0]), float(X.mean()[0]))
sepal_width = st.slider('Sepal width (cm)', float(X.min()[1]), float(X.max()[1]), float(X.mean()[1]))
petal_length = st.slider('Petal length (cm)', float(X.min()[2]), float(X.max()[2]), float(X.mean()[2]))
petal_width = st.slider('Petal width (cm)', float(X.min()[3]), float(X.max()[3]), float(X.mean()[3]))

# Make prediction
input_data = [[sepal_length, sepal_width, petal_length, petal_width]]
prediction = clf.predict(input_data)
predicted_class = iris.target_names[prediction[0]]

st.subheader("Prediction:")
st.write(f"The predicted iris species is **{predicted_class}**.")